apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv  # Nama Persistent Volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi  # Kapasitas penyimpanan yang dialokasikan
  accessModes:
    - ReadWriteOnce  # Mode akses: satu node pembaca-tulis
  hostPath:
    path: /data/db 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc  # Nama Persistent Volume Claim
spec:
  storageClassName: manual  # Nama kelas penyimpanan yang sesuai dengan PV
  accessModes:
    - ReadWriteOnce  # Mode akses: satu node pembaca-tulis
  resources:
    requests:
      storage: 1Gi  # Permintaan kapasitas penyimpanan
