apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: karsajobs
    tier: backend
spec:
  selector:
    app: karsajobs
    tier: backend
  ports:
    - protocol: TCP # Menentukan protokol sebagai TCP
      port: 27017     # Port yang digunakan pada Layanan
      targetPort: 27017 # Port yang digunakan pada pod
  clusterIP: None