apiVersion: v1 # Versi
kind: Secret # jenis resource, dalam hal ini adalah Secret
metadata:
  name: mongo-secret # Nama ConfigMap untuk konfigurasi mongo-secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: # base64-encoded value "admin"
  MONGO_ROOT_PASSWORD:  # base64-encoded value "supersecretpassword"
