apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: karsajobs-db
  labels:
    app: karsajobs
    tier: backend
spec:
  serviceName: karsajobs-db
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
      tier: backend
  template:
    metadata:
      labels:
        app: karsajobs
        tier: backend
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          #Atur semua environment variable yang dibutuhkan
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE 
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          volumeMounts:
            - name: pv
              mountPath: /data/db
            - name: config
              mountPath: /config
            - name: secret
              mountPath: /etc/mongo-credentials
      volumes:
      - name: pv
        persistentVolumeClaim:
          claimName: mongo-pvc
      - name: config
        configMap:
          name: mongo-configmap
          items:
            - key: mongo.conf
              path: mongo.conf
      - name: secret
        secret:
          secretName: mongo-secret