apiVersion: v1 # Versi
kind: Secret # jenis resource, dalam hal ini adalah Secret
metadata:
  name: mongo-secret # Nama ConfigMap untuk konfigurasi mongo-secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=  # base64-encoded value "admin"
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwb3NzcGFzc3dvcmQ=  # base64-encoded value "supersecretpassword"
