# versi pertama dari API Kubernetes
apiVersion: v1
# jenis resource, dalam hal ini adalah Service
kind: Service
metadata:
# nama dari servicenya
  name: karsajobs-service
  # Labeling app karsajobs dan tier sebagai backend
  labels:
    app: karsajobs
    tier: backend
spec:
  selector:
    # pilih pod yang diinginkan, dalam hal ini 'app: karsajobs'
    app: karsajobs
  ports:
    # menggunakan TCP sebagai protokol
    - protocol: TCP
    # set port untuk mendengarkan
      port: 80
    # meneruskan ke port 8080 pada pod
      targetPort: 8080
  # menggunakan LoadBalancer
  type: LoadBalancer
