# versi pertama dari API Kubernetes
apiVersion: v1
# jenis resource, dalam hal ini adalah Service
kind: Service
metadata:
# nama dari servicenya
  name: karsajobs-ui
# Labeling app karsajobs dan tier sebagai backend
  labels:
    app: karsajobs
    tier: frontend
spec:
  selector:
    app: karsajobs # Memilih pod dengan label 'app: karsajobs' dan 'tier: frontend'
    tier: frontend
  ports:
    - protocol: TCP # Menentukan protokol sebagai TCP
      port: 8000      # Port yang digunakan pada Layanan
      targetPort: 8000  # Update to match the container port
  type: NodePort  # Jenis Layanan, dalam hal ini NodePort