name: Continuous Integration

on:
  push:
    branches:
      - karsajobs
      - karsajobs-ui

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install hadolint
        run: |
          wget https://github.com/hadolint/hadolint/releases/download/v2.4.1/hadolint-Linux-x86_64
          chmod +x hadolint-Linux-x86_64
          sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
        shell: bash

      - name: Lint Dockerfile
        run: hadolint Dockerfile
        shell: bash

  karsajobs-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests for backend
        run: go test -v -short --count=1 $(go list ./...)

  karsajobs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u mueiya --password-stdin

      - name: Build and push backend image
        run: docker build -t ghcr.io/mueiya/karsajobs:latest . && docker push ghcr.io/mueiya/karsajobs:latest
